#include<iostream>

using namespace std;

int main()
{
    cout << "Hello, welcome to ";
    cout << 'Y';
    cout << 'o';
    cout << 'u';
    cout << 'r';
    cout << 'V';
    cout << 'e';
    cout << 'r';
    cout << 'y';
    cout << 'T';
    cout << 'r';
    cout << 'u';
    cout << 's';
    cout << 't';
    cout << 'w';
    cout << 'o';
    cout << 'r';
    cout << 't';
    cout << 'h';
    cout << 'y';
    cout << 'D';
    cout << 'e';
    cout << 'l';
    cout << 'i';
    cout << 'v';
    cout << 'e';
    cout << 'r';
    cout << 'y';
    cout << 'S';
    cout << 'e';
    cout << 'r';
    cout << 'v';
    cout << 'i';
    cout << 'c';
    cout << 'e';
    cout << 'T';
    cout << 'h';
    cout << 'a';
    cout << 't';
    cout << 'D';
    cout << 'e';
    cout << 'f';
    cout << 'i';
    cout << 'n';
    cout << 'e';
    cout << 't';
    cout << 'l';
    cout << 'y';
    cout << 'W';
    cout << 'i';
    cout << 'l';
    cout << 'l';
    cout << 'N';
    cout << 'o';
    cout << 't';
    cout << 'S';
    cout << 't';
    cout << 'e';
    cout << 'a';
    cout << 'l';
    cout << 'Y';
    cout << 'o';
    cout << 'u';
    cout << 'r';
    cout << 'P';
    cout << 'a';
    cout << 'c';
    cout << 'k';
    cout << 'a';
    cout << 'g';
    cout << 'e';
    cout << 's';
    cout << 'M';
    cout << 'a';
    cout << 'y';
    cout << 'b';
    cout << 'e';
    cout << 'I';
    cout << 't';
    cout << 'R';
    cout << 'e';allyDependsOnHowHungryIAmBecauseIHaveAFamilyToFeedSorryManItsNotMyFaultWeLiveInThisCapitalismEconomy's website!\nWe Hope you can safely deliver your packages!\n";
    cout << "To start, we have to know your package's weight"
}